; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[absolute_messages][version] = "1.3"

projects[adaptive_image][version] = "1.4"

projects[addressfield][version] = "1.0-beta4"

projects[addressfield_phone][version] = "1.1"

projects[advanced_help][version] = "1.0"

projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][version] = "2.5"

projects[block_class][version] = "2.0"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.13"

projects[context][version] = "3.0-beta6"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[draggableviews][version] = "2.0"

projects[drupalforfirebug][version] = "1.4"

projects[fontyourface][version] = "2.8"

projects[elements][version] = "1.3"

projects[entity][version] = "1.0"

projects[entityreference][version] = "1.0"

projects[exclude_node_title][version] = "1.6"

projects[faq][version] = "1.0-rc2"

projects[fences][version] = "1.0"

projects[field_group][version] = "1.1"

projects[field_reference][version] = "1.0"

projects[forgotten_login][version] = "1.1"

projects[html5_tools][version] = "1.2"

projects[imce][version] = "1.7"

projects[jquery_update][version] = "2.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[fitt][download][type] = ""
projects[fitt][download][url] = ""
projects[fitt][type] = "module"
projects[fitt][version] = "1.1"

projects[libraries][version] = "2.1"

projects[link][version] = "1.1"

projects[linkchecker][version] = "1.1"

projects[logintoboggan][version] = "1.3"

projects[logo_block][version] = "1.6"

projects[masquerade][version] = "1.0-rc5"

projects[menu_block][version] = "2.3"

projects[menu_token][version] = "1.0-beta4"

projects[module_filter][version] = "1.7"

projects[mollom][version] = "2.6"

projects[node_class][version] = "1.1"

projects[references][version] = "2.1"

projects[panels][version] = "3.3"

projects[path_breadcrumbs][version] = "3.0-beta2"

projects[pathauto][version] = "1.2"

projects[pathologic][version] = "2.10"

projects[profile2][version] = "1.3"

projects[r4032login][version] = "1.5"

projects[rules][version] = "2.3"

projects[simplenews][version] = "1.0"

projects[socialmedia][version] = "1.0-beta13"

projects[special_menu_items][version] = "2.0"

projects[stringoverrides][version] = "1.8"

projects[styleguide][version] = "1.1"

projects[superfish][version] = "1.9"

projects[tabname_tweaker][version] = "1.1"

projects[terms_of_use][version] = "1.2"

projects[tinynav][version] = "1.2"

projects[token][version] = "1.5"

projects[user_register_notify][version] = "1.0-alpha2"

projects[user_settings_access][version] = "1.0"

projects[views][version] = "3.7"

projects[views_accordion][version] = "1.0-rc2"

projects[views_calc][version] = "1.0"

projects[views_field_view][version] = "1.0"

projects[webform][version] = "3.18"

projects[widgets][version] = "1.0-rc1"

projects[zenophile][version] = "1.1"

; Themes
projects[zen][version] = "5.1"

projects[kwealth][type] = "theme"
projects[kwealth][download][type] = "git"
projects[kwealth][download][url] = "https://github.com/mooru/kwealth.git"
projects[kwealth][download][revision] = "10af5fcac664abec8a5baf4e3b0aea85e49d9fcf"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = ""
libraries[chosen][download][url] = ""
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[PHPExcel][download][type] = ""
libraries[PHPExcel][download][url] = ""
libraries[PHPExcel][directory_name] = "PHPExcel"
libraries[PHPExcel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tcpdf][download][type] = ""
libraries[tcpdf][download][url] = ""
libraries[tcpdf][directory_name] = "tcpdf"
libraries[tcpdf][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ZendGdata][download][type] = ""
libraries[ZendGdata][download][url] = ""
libraries[ZendGdata][directory_name] = "ZendGdata"
libraries[ZendGdata][type] = "library"

