<?php


function kwealth_form_contact_site_form_alter(&$form, &$form_state, $form_id) {
//krumo($form);
global $user;
$form['name']['#title'] = 'Name';
$form['mail']['#title'] = 'E-Mail';
$form['actions']['submit']['#value'] = 'Submit';
}

function kwealth_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  $form['account']['name']['#title'] = 'Church';
}

function kwealth_form_alter(&$form, &$form_state, $form_id) {
 global $user;
  if ($user->uid == 0) {
  if ($form_id == 'user_register_form'){
  $form['actions']['submit']['#value'] = t('Sign Up');
  }
}
}

function kwealth_menu() {
 $items['user/%user/loan'] = array(
    'title' => 'Loan',
    'page callback' => 'node_page_view',
    'page arguments' => array(node_load(23)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
  $items['user/%user/loan/guidelines'] = array(
    'title' => 'Loan Guidelines',
    'page callback' => 'node_page_view',
    'page arguments' => array(node_load(23)),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
   $items['user/%user/loan/forms'] = array(
    'title' => 'Loan Forms and Calculator',
    'page callback' => 'node_page_view',
    'page arguments' => array(node_load(26)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
    $items['user/%user/loan/guarantor'] = array(
    'title' => 'Guarantor Guideline',
    'page callback' => 'node_page_view',
    'page arguments' => array(node_load(43)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
     $items['user/%user/membership'] = array(
    'title' => 'Exit',
    'page callback' => 'node_page_view',
    'page arguments' => array(node_load(25)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
    $items['user/%user/contribution/guidelines'] = array(
    'title' => 'Guidelines',
   'page callback' => 'node_page_view',
    'page arguments' => array(node_load(22)),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
     $items['user/%user/contribution'] = array(
    'title' => 'Contributions',
   'page callback' => 'node_page_view',
    'page arguments' => array(node_load(22)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
    $items['user/%user/equipment'] = array(
    'title' => 'Equipment',
   'page callback' => 'node_page_view',
    'page arguments' => array(node_load(44)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
    $items['user/%user/equipment'] = array(
    'title' => 'Equipment Guidelines',
   'page callback' => 'node_page_view',
    'page arguments' => array(node_load(44)),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
    $items['user/%user/equipment/form'] = array(
    'title' => 'Asset Finance Form',
   'page callback' => 'node_page_view',
    'page arguments' => array(node_load(45)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

// function kwealth_menu_alter(&$items) {
//     $items['user/%user/view']['title'] = "Profile";
//     $items['user/%user/edit']['title'] = "Edit Profile";
//     $items['user/%user/edit']['weight'] = -1;


//     return $items;
// }
// 

/**
 * Implements hook_menu_link_alter().
 */
function kwealth_menu_link_alter(&$item) {
  // Example 1 - make all new admin links hidden (a.k.a disabled).
  /*
   *if (strpos($item['link_path'], 'admin') === 0 && empty($item['mlid'])) {
   *  $item['hidden'] = 1;
   *}
   */
  // Example 2  - flag a link to be altered by hook_translated_menu_link_alter()
  /*
   *if ($item['link_path'] == 'devel/cache/clear') {
   *  $item['options']['alter'] = TRUE;
   *}
   */
  /* Your code here */
  if ($item['link_path'] == 'user/%'){
    $item['link_title'] = 'Profile';
  }
    if ($item['link_path'] == 'user/%/edit'){
    $item['link_title'] = 'Edit Profile';
  }
}

